# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "home-work"
	LogPath     = "tmp/log/homework/server"
	logStdout           = true               # 日志是否输出到终端。默认为true
	errorStack          = true               # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
	errorLogEnabled     = true               # 是否记录异常日志信息到日志中。默认为true
	errorLogPattern     = "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
	accessLogEnabled    = false              # 是否记录访问日志。默认为false
	accessLogPattern    = "access-{Ymd}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"
	# PProf配置
	pprofEnabled        = false              # 是否开启PProf性能调试特性。默认为false
	pprofPattern        = ""                 # 开启PProf时有效，表示PProf特性的页面访问路径，对当前Server绑定的所有域名有效。
	debug               = true

# Logger.
[logger]
    Path        = "tmp/log/homework"
    Level       = "all"
    Stdout      = true